before:
  hooks:

builds:
  - main: cmd/ephemerald/main.go
    ldflags:
      - -s -w -X github.com/boz/ephemerald/version.version={{.Version}} -X github.com/boz/ephemerald/version.commit={{.FullCommit}} -X github.com/boz/ephemerald/version.date={{.Date}}
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386

archives:
  - files:
    - none*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - github:
      owner: boz
      name: homebrew-repo
    homepage: "https://github.com/boz/ephemerald"
    description: "Manage ephemeral docker containers for parallel testing."
