language: go
services:
  - docker

go:
  - 1.12

cache:
  directories:
  - $HOME/.glide/cache

before_install:
  - curl https://glide.sh/get | sh
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - make deps

jobs:
  include:
    - script:
      - .build/test
      - go vet ./...
      - golangci-lint run
