language: go
services:
  - docker

go:
  - 1.12

before_install:
  - curl https://glide.sh/get | sh

install:
  - make deps

jobs:
  include:
    - stage: Build
      script:
        - go build ./...
    - stage: Vet
      script:
        - go vet ./...
    - stage: Test
      script:
        - go test -count=1 -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

