---
pools:
  redis:
    image: redis
    size: 5
    port: 6379
    params:
      database: "0"
      url: redis://{{.Hostname}}:{{.Port}}/{{.Database}}
    actions:
      live:
        type: redis.ping
      reset:
        type: redis.truncate
  postgres:
    image: postgres
    size: 5
    port: 5432
    params:
      username: postgres
      database: postgres
      url: postgres://{{.Username}}:{{.Password}}@{{.Hostname}}:{{.Port}}/{{.Database}}?sslmode=disable
    actions:
      live:
        type: postgres.ping
      init:
        type: postgres.exec
        query: |
          CREATE TABLE users (
            id SERIAL PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            UNIQUE(name)
          )
      reset:
        type: postgres.truncate
